name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo +beta build --verbose
      - name: Run tests
        run: cargo +beta test --verbose
      - name: Check formating
        run: |
          rustup component add rustfmt
          cargo +beta fmt --all -- --check
      - name: Check code issues
        run: |
          rustup component add clippy
          cargo +beta clippy --all -- -D warnings
